### ISSUE TITLE
Site down: nature-of-computation.org

### ISSUE THREAD

**Issue by willisman31** [mostafatouny/awesome-theoretical-computer-science#1]
nature-of-computation.org has been inaccessible for several days, both from the link and through browsing.  The book in its entirety is currently offered free through (scribd)[https://www.scribd.com/document/420543111/Cristopher-Moore-Stephan-Mertens-The-Nature-of-Computation-2011-pdf]

**Comment by mostafatouny** [comment]
Thanks! Would you _pull request_ with your updated link? Just modify _source.json_ in *big_list_builder* folder and execute _run.sh_. It shall produce the _README.md_ file.

Let me know if you faced any technical issue.
